/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ConfiguracionMediosIndexImport } from './routes/configuracion/medios/index'
import { Route as ConfiguracionMediosWizardStepImport } from './routes/configuracion/medios/wizard.$step'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ConfiguracionMediosIndexRoute = ConfiguracionMediosIndexImport.update({
  id: '/configuracion/medios/',
  path: '/configuracion/medios/',
  getParentRoute: () => rootRoute,
} as any)

const ConfiguracionMediosWizardStepRoute =
  ConfiguracionMediosWizardStepImport.update({
    id: '/configuracion/medios/wizard/$step',
    path: '/configuracion/medios/wizard/$step',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/configuracion/medios/': {
      id: '/configuracion/medios/'
      path: '/configuracion/medios'
      fullPath: '/configuracion/medios'
      preLoaderRoute: typeof ConfiguracionMediosIndexImport
      parentRoute: typeof rootRoute
    }
    '/configuracion/medios/wizard/$step': {
      id: '/configuracion/medios/wizard/$step'
      path: '/configuracion/medios/wizard/$step'
      fullPath: '/configuracion/medios/wizard/$step'
      preLoaderRoute: typeof ConfiguracionMediosWizardStepImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion/medios': typeof ConfiguracionMediosIndexRoute
  '/configuracion/medios/wizard/$step': typeof ConfiguracionMediosWizardStepRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion/medios': typeof ConfiguracionMediosIndexRoute
  '/configuracion/medios/wizard/$step': typeof ConfiguracionMediosWizardStepRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/configuracion/medios/': typeof ConfiguracionMediosIndexRoute
  '/configuracion/medios/wizard/$step': typeof ConfiguracionMediosWizardStepRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion/medios'
    | '/configuracion/medios/wizard/$step'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracion/medios' | '/configuracion/medios/wizard/$step'
  id:
    | '__root__'
    | '/'
    | '/configuracion/medios/'
    | '/configuracion/medios/wizard/$step'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionMediosIndexRoute: typeof ConfiguracionMediosIndexRoute
  ConfiguracionMediosWizardStepRoute: typeof ConfiguracionMediosWizardStepRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionMediosIndexRoute: ConfiguracionMediosIndexRoute,
  ConfiguracionMediosWizardStepRoute: ConfiguracionMediosWizardStepRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/configuracion/medios/",
        "/configuracion/medios/wizard/$step"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/configuracion/medios/": {
      "filePath": "configuracion/medios/index.tsx"
    },
    "/configuracion/medios/wizard/$step": {
      "filePath": "configuracion/medios/wizard.$step.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
