name = "descuentito"
main = "./.output/server/index.mjs"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-02-14"
observability = { enabled = true }

[assets]
directory = "./.output/public"
binding = "ASSETS"

# KV Namespace binding from the original wrangler.jsonc
[[kv_namespaces]]
binding = "DESCUENTITO_DATA"
id = "f207d1c49cc144ac893eb40be075bd0d" 

[vars]
BUN_VERSION = "1.2.11"
SKIP_DEPENDENCY_INSTALL = true
# LINEAR_TEAM_ID can be public as it's not sensitive
LINEAR_TEAM_ID = "b2a4ca1f-7ff1-4e91-9ddb-a024b7d115c1"